# Generated by Django 6.1.1 on 2026-09-25 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('intent', models.CharField(choices=[('create', 'Create'), ('join', 'Join'), ('reauth', 'Reauth')], max_length=15)),
                ('attempts_left', models.IntegerField(default=5)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EscrowContract',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_payer', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], max_length=10)),
                ('creator_email', models.EmailField(db_index=True, max_length=254)),
                ('creator_role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], max_length=10)),
                ('counterparty_email', models.EmailField(db_index=True, max_length=254)),
                ('status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('awaiting_counterparty', 'Awaiting Counterparty'), ('awaiting_funding', 'Awaiting Funding'), ('in_inspection', 'In Inspection'), ('pending_payout', 'Pending Payout'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='pending_verification', max_length=30)),
                ('inspection_days', models.IntegerField(default=3)),
                ('inspection_ends', models.DateTimeField(blank=True, null=True)),
                ('buyer_confirmed', models.BooleanField(default=False)),
                ('seller_confirmed', models.BooleanField(default=False)),
                ('gateway_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SettlementVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_code', models.CharField(max_length=10)),
                ('account_number', models.CharField(max_length=10)),
                ('account_name', models.CharField(max_length=150)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_vault', to='escrow.escrowcontract')),
            ],
        ),
    ]
