# Generated by Django 6.1.1 on 2026-09-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowcontract',
            name='status',
            field=models.CharField(choices=[('pending_verification', 'Pending Verification'), ('awaiting_counterparty', 'Awaiting Counterparty'), ('awaiting_funding', 'Awaiting Funding'), ('awaiting_dispatch', 'Awaiting Dispatch'), ('in_transit', 'In Transit'), ('in_inspection', 'In Inspection'), ('pending_payout', 'Pending Payout'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='pending_verification', max_length=30),
        ),
    ]
